apiVersion: v2
name: wspieramprzyrode
description: Wspieramprzyrode Web application
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: inventory
    file: "charts/inventory"
    condition: inventory.enabled