{{- if .Values.cloudflare.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-key: {{ .Values.cloudflare.apiToken }}
{{- end }}
