{{- if .Values.cloudflare.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare.apiToken | b64enc }}
{{- end }}
