name: Inventory service
on:
  push:
    paths:
      - .github/workflows/inventory_service.yaml
      - inventory/**
defaults:
  run:
    working-directory: inventory
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - name: Cache golang modules
      uses: actions/cache@v1
      env:
        cache-name: cache-inventory-go-dependencies
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-inventory
    - name: Install
      run: go mod download
    - name: Test
      run: go test ./...
    - name: Build
      run: go build -o bin/inventory main.go
    - name: Lint Helm
      uses: WyriHaximus/github-action-helm3@master
      with:
        exec: helm lint ./chart/
  docker-build:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Push and Deploy
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: benjlevesque/short-sha@v1.1
      id: short-sha
    - name: Publish to docker registry
      id: docker-push
      uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: wspieramprzyrode/inventory
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: inventory
        image_tag: ${{ steps.short-sha.outputs.sha }}
    - name: Deploy
      uses: WyriHaximus/github-action-helm3@master
      with:
        exec: helm upgrade --install --wait --atomic  --reuse-values  --namespace=dev --set=inventory.image.tag=${{ steps.short-sha.outputs.sha }} --values=./deploy-dev.yaml wspieramprzyrode ./chart/
        kubeconfig: '${{ secrets.KUBE_CONFIG }}'
